### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by paulblyth** [kerimdzhanov/dotenv-flow-webpack#15]
Hi @kerimdzhanov thanks for the package, I've just started using it in a Webpack 5 project, and it seems to be working as expected.

Are there any tests I can run to fully validate compatibility? If I can do that I'd be happy to submit a PR to add 5 to the supported peer deps.

**Comment by chenop** [comment]
Tried to install "^1.1.0", got:
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^1 || ^2 || ^3 || ^4" from dotenv-flow-webpack@1.1.0
npm ERR! node_modules/dotenv-flow-webpack
npm ERR!   dev dotenv-flow-webpack@"^1.1.0" from the root project

So I dont think its working as expected.
Any heads up when it will be updated? alternative package?

**Comment by tlarsonlgdor** [comment]
Yes. Please provide update for Webpack 5 or an alternative package.

**Comment by spassvogel** [comment]
Another vote to have this merged please
