### ISSUE TITLE
publish to NPM

### ISSUE THREAD

**Issue by spassvogel** [kerimdzhanov/dotenv-flow-webpack#22]
Now that webpack 5 is a peer dep, can this be published to the npm repository?

**Comment by kerimdzhanov** [comment]
Hi @spassvogel,

Yeah, sorry for the delay.

I published a [release candidate](https://github.com/kerimdzhanov/dotenv-flow-webpack/releases/tag/v1.2.0-rc.1). It's now available in npm repo via `npm install dotenv-flow-wepack@next`, please give it a try. If everything is okay, I'll release it as a stable in a few days.

**Comment by spassvogel** [comment]
> Hi @spassvogel,
> 
> Yeah, sorry for the delay.
> 
> I published a [release candidate](https://github.com/kerimdzhanov/dotenv-flow-webpack/releases/tag/v1.2.0-rc.1). It's now available in npm repo via `npm install dotenv-flow-webpack@next`, please give it a try. If everything is okay, I'll release it as a stable in a few days.

Cool thx! It seems to work well!

**Comment by kerimdzhanov** [comment]
[v1.2.0 with webpack@5 support](https://github.com/kerimdzhanov/dotenv-flow-webpack/releases/tag/v1.2.0) has been released.

Thanks for checking @spassvogel!
